# Generated by Django 4.1 on 2022-08-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_vers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('description', models.TextField(blank=True, null=True)),
                ('url1', models.CharField(blank=True, max_length=100, null=True)),
                ('url2', models.URLField(blank=True, null=True)),
                ('upload_date', models.DateField(auto_now=True)),
                ('upload_by', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_by_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
