# Generated by Django 4.1 on 2022-08-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_vers', '0002_photography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
