# Generated by Django 4.1 on 2022-09-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_vers', '0006_alter_contact_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/contact/'),
        ),
    ]
